name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message), ', '), '#skip')}}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        id: deploy
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bloglist-ci-cd"
          heroku_email: "orazurobert@yahoo.com"
          healthcheck: "https://bloglist-ci-cd.herokuapp.com"
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - name: Slack notification
        if: ${{ steps.deploy.outcome = "success"}}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `a new version deployed to https://bloglist-ci-cd.herokuapp.com/ (${process.env.AS_COMMIT})\nby ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
