name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  pipeline_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          cd frontend && ls
